baseURL = "https://chrishorner.codes"
languageCode = "en-au"
title = "Chris Horner"
author = "Chris Horner"
pygmentsUseClasses = true
pygmentsCodefences = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup.goldmark.renderer]
unsafe= true
