baseurl = "http://chrishorner.codes/"
languageCode = "en-us"
title = "Chris Horner"
theme = "hugo-creative-theme"
pygmentsstyle = "colorful"
# pygmentuseclasses= true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Chris Horner"
	description = "Android developer and designer"

  blogPath = "/blog"

	# Navigation
	[params.navigation]
		brand = "Chris Horner"

		[params.navigation.links]
			about     = "About"
			portfolio = "Portfolio"
      blog = "Blog"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Android dev & designer"
		subtitle   = "I'm Chris, and I like to build apps with a strong focus on UX.<br/><br/>One day I'll make games."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Who am I?"
		description = "I'm a developer who likes to make cool things.<br/><br/>I studied games development at Swinburne University (comp sci / multimedia). In my final year I focused on building Android games. Now I make apps.<br/><br/>I'm currently lead Android developer at Melbourne based [Gridstone](//gridstone.com.au), where I've been building apps for four years."
		buttonText  = "Which apps?"

  [params.portfolio]
        headline = "Portfolio"

  # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"
        linkTitle = "View in Play Store"

  # Blod section
	[params.blog]
		headline = "Blog"
    description = "I also write about Android design and development."

		[params.blog.button]
			text = "Read it"

	# Contact section
	[params.contact]
		headline = "Contact"
    github = "chris-horner"
    twitter = "chadefarseer"

