baseurl = "http://127.0.0.1:1313/"
languageCode = "en-us"
title = "Chris Horner"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Chris Horner"
	description = "Android developer and designer"


	# Navigation
	[params.navigation]
		brand = "Chris Horner"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Android dev & designer"
		subtitle   = "I'm Chris, and I like to build apps with a strong focus on UX.<br/><br/>One day I'll make games."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Who am I?"
		description = "I'm a developer who likes to make cool things.<br/><br/>I studied games development at Swinburne University (comp sci / multimedia). In my final year I focused on building Android games. Now I make apps.<br/><br/>I'm currently lead Android developer at Melbourne based [Gridstone](//gridstone.com.au), where I've been building apps for four years."
		buttonText  = "Which apps?"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Sturdy Templates"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "You have to make your websites with love these days!"

  [params.portfolio]
        headline = "Portfolio"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"
        linkTitle = "View in Play Store"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "horner.cd@gmail.com"
